name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false # 禁用 submodule 同步

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.151.2'

      - name: Build site
        run: hugo --minify --themesDir ./themes # 確保 themes 路徑正確

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
